#!/usr/bin/php -q
<?php
define('UI', 'CLI');
define('CLI', 'moojon_cli');
define('ENVIRONMENT', 'production');
define('MOOJON_DIRECTORY', dirname(__FILE__).'/');
define('MOOJON_VERSION', basename(MOOJON_DIRECTORY));
require_once('moojon.php');
?>