#!/Applications/MAMP/bin/php5/bin/php
<?php
require_once 'growl.php';
abstract class moojon_base_test {
	private $growl;
	final public function __construct() {
		$this->growl =& Net_Growl::singleton('Net_Growl', array('Messages'));
		try {
			$this->init();
			$this->run();
		} catch (Exception $exception) {
			echo "Oh dear. Something went wrong:\n";
			echo $exception->getMessage();
			echo "\n";
		}
		//$this->notify();
	}
	
	final public function __destruct() {
		try {
			$this->close();
		} catch (Exception $exception) {
			echo "Oh dear. Something went wrong:\n";
			echo $exception->getMessage();
			echo "\n";
		}
	}
	
	final private function notify() {
		$this->growl->notify('Messages', 'Hello', 'How are you ?');
	}
	
	protected function init() {}
	
	abstract protected function run();
	
	protected function close() {}
	
	final protected function assert() {}
}
class moojon_cli_test extends moojon_base_test {
	final protected function init() {
		exec('moojon testing2.dev client index index');
		echo time()."\n";
	}
	
	final protected function run() {}
	
	final protected function close() {
		$dir = '~/Moojon/testing2.dev';
		exec("sudo rm -rf $dir");
	}
}
while (1) {
	$test = new moojon_cli_test();
	//sleep(2);
	unset($test);
	//sleep(2);
}
?>