#!/Applications/MAMP/bin/php5/bin/php
<?php
abstract class moojon_base_test {
	final public function __construct() {
		try {
			$this->init();
			$this->run();
		} catch (Exception $exception) {
			echo "Oh dear. Something went wrong:\n";
			echo $exception->getMessage();
			echo "\n";
		}
	}
	
	final public function __destruct() {
		try {
			$this->close();
		} catch (Exception $exception) {
			echo "Oh dear. Something went wrong:\n";
			echo $exception->getMessage();
			echo "\n";
		}
	}
	
	protected function init() {}
	
	abstract protected function run();
	
	protected function close() {}
	
	final protected function assert() {}
}
class moojon_cli_test extends moojon_base_test {
	final protected function init() {
		exec('moojon testing2.dev client index index');
	}
	
	final protected function run() {
		echo "run\n";
	}
	
	final protected function close() {
		$dir = $_SERVER['PWD'].'/testing2.dev';
		exec("rm -rf $dir");
	}
}
while (1) {
	$test = new moojon_cli_test();
	sleep(2);
	unset($test);
	sleep(2);
}
?>