#!/Applications/MAMP/bin/php5/bin/php
<?php
define('MOOJON_VERSION', '0.1');
define('MOOJON_PATH', '/Library/Moojon/'.MOOJON_VERSION.'/');
define('ENVIRONMENT', 'development');
define('UI', 'CLI');
define('CLI', 'moojon_cli');
require_once(MOOJON_PATH.'/moojon.php');
?>