#!/Applications/MAMP/bin/php5/bin/php
<?php
define('UI', 'CLI');
define('CLI', 'moojon_generate_cli');
define('PROJECT_DIRECTORY', $_SERVER['DOCUMENT_ROOT'].'/../');
require_once(PROJECT_DIRECTORY.'config/constants.php');
require_once(MOOJON_PATH.'moojon.php');
?>