#!/Applications/MAMP/bin/php5/bin/php
<?php
define('UI', 'CLI');
define('CLI', 'moojon_migrate_cli');
require_once(dirname(dirname(__FILE__)).'/config/constants.php');
require_once(MOOJON_DIRECTORY.'moojon.php');
?>