#!/Applications/MAMP/bin/php5/bin/php
<?php
define('UI', 'CLI');
define('CLI', 'moojon_pluggin_cli');
require_once(dirname(__FILE__).'/../config/constants.php');
require_once(MOOJON_DIRECTORY.'moojon.php');
?>